[package]
name = "mdbook-leptos"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
cargo-leptos = "0.2.7"
clap = { version = "4.1.6", features = ["derive"] }
dotenvy = "0.15.7"
git2 = "0.18.2"
inquire = "0.6.2"
leptos = "0.6.5"
once_cell = "1.19.0"
serde = { version = "1.0.196", features = ["derive", "serde_derive"] }
toml = "0.8.10"

[lib]
name = "lib"
parh = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"
